version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 355687610926.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t html-demo .
      - docker tag html-demo:latest 355687610926.dkr.ecr.us-east-1.amazonaws.com/html-demo:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 355687610926.dkr.ecr.us-east-1.amazonaws.com/html-demo:latest
      - echo Build complete.
